TexasInstruments/edgeai-gst-plugins

gst-libs/gst/tiovx/gsttiovxmeta.c

Fix to support IYVU and YUV4 image format types

Fix to support IYUV and YUV4 formats

---

ext/tiovx/gsttiovxcolorconvert.c
ext/tiovx/gsttiovxmultiscaler.c
pkgconfig/vision_apps_modules.pc

Signed-off-by: Shyam Jagannathan <a0393891@ti.com>

modules-phase-1.2: updated colorconvert and multiscaler apis

---

gst-libs/gst/tiovx/gsttiovxcontext.c

-Call app init conditionally by reading
SKIP_TIOVX_INIT environment variable

app-init:call app-init conditionally

---

README.md
gst-libs/gst/tiovx/gsttiovxcontext.c
gst-libs/gst/tiovx/meson.build
meson.build
pkgconfig/edgeai_tiovx_modules.pc
pkgconfig/ti_vision_apps.pc

Signed-off-by: Shyam Jagannathan <a0393891@ti.com>

build: cleanup and update to work with PSDK 8.0

---

gst-libs/gst/tiovx/gsttiovxsimo.c

Copy input buffer timestamps info to the output buffers

---

ext/tiovx/gsttiovxdlpreproc.c
gst-libs/gst/tiovx/gsttiovx.h
gst-libs/gst/tiovx/gsttiovxmiso.c
gst-libs/gst/tiovx/gsttiovxsimo.c
gst-libs/gst/tiovx/gsttiovxsiso.c
gst-libs/gst/tiovx/gsttiovxutils.c

Signed-off-by: Shyam Jagannathan <a0393891@ti.com>

img_proc: fixed img_proc kernel load/unload location

---

gst-libs/gst/tiovx/gsttiovxsimo.c

This fixes a memory leak, where after adquiring all input buffers, if
one failed to push not all inputs were released. This fix attempts to
push to all pads, which correctly release all input buffers and allows
the corresponding bufferpool to be released.

Hotfix: Attempt to push buffer to all pads after error

---

ext/tiovx/gsttiovx.c
gst-libs/gst/tiovx/gsttiovxutils.c
gst-libs/gst/tiovx/gsttiovxutils.h

Initialize GST_PERFORMANCE debug category

---

gst-libs/gst/tiovx/gsttiovxsimo.c

This solves issues #187 and #90

Downgrade error to warning

---

pkgconfig/edgeai_tiovx_modules.pc

Please refer to
https://github.com/TexasInstruments/edgeai-tiovx-modules/commit/1e0fa6533f076d98cbcd2808ef160648a722b3cc
for changes done in modules

pkgconfig: edgeai_tiovx_modules: Modify as per the changes in modules repo

---

ext/tiovx/gsttiovxldc.c

Add properties to configure crop out block width/height and pixel padding for LDC

ext: tiovx: ldc: Add properties to configure block params

---

ext/tiovx/gsttiovxisp.c
ext/tiovx/gsttiovxldc.c

Add list of sensor in the description,
which gets printed in gst-inspect

ext: tiovx: ldc/isp: Add list of sensors

---

ext/tiovx/gsttiovxmosaic.c

mosaic: Fix resize issue, width was used instead of height

---

ext/tiovx/gsttiovxmosaic.c

Mosaic fixate caps was doing intersect full which
compares many irrelavant caps. This broke mosaic
when there were minor changes among the input-stream.
For example, if pixel-aspect-ratio is different among inputs, mosaic fails
Fix this by comparing only format in fixate caps

ext: tiovx: mosaic: Fix the fixate caps for mosaic

---

ext/tiovx/gsttiovx.c
ext/tiovx/gsttiovxcolorconvert.c
ext/tiovx/gsttiovxdlcolorblend.c
ext/tiovx/gsttiovxdlcolorconvert.c
ext/tiovx/gsttiovxdlpreproc.c
ext/tiovx/gsttiovxdofviz.c
ext/tiovx/gsttiovxsdeviz.c
ext/tiovx/meson.build
meson.build

ext/meson: Add support fo J78484

---

pkgconfig/ti_stereo_perception.pc

Perception include folder name is changed in SDK.
Align with the same

pkgconfig: ti_stereo_perception: Align with updates in SDK

---

ext/tiovx/gsttidlpostproc.cpp
ext/tiovx/gsttidlpostproc.h
ext/tiovx/gsttiovx.c
ext/tiovx/meson.build
pkgconfig/edgeai_dl_inferer.pc

Add a gst plugins which overlay DL Inference
results on the input image

ext: ti: Add gst plugin for DL Post Process

---

ext/tiovx/gsttiovx.c
ext/tiovx/gsttiperfoverlay.cpp
ext/tiovx/gsttiperfoverlay.h
ext/tiovx/meson.build

Add a gst plugins which overlay performance
stats on NV12 image

ext: ti: Add gst plugin for Performance Overlay

---

ext/tiovx/gsttidlinferer.cpp
ext/tiovx/gsttidlpostproc.cpp
ext/tiovx/gsttiperfoverlay.cpp

edgeai-dl-inferer has been restructured. Change in dlinferer, dlpostproc and perfoverlay plugin accordingly. Also UI Cleanup in perfoverlay

ext: tiovx: Changes corresponding to latest dl-inferer change

---

ext/tiovx/gsttiperfoverlay.cpp

Count number of graphs that needs to be drawn to report stats in the first call of the chain function

ext: tiovx: gsttiperfoverlay Bug fix for counting number of graphs

---

gst-libs/gst/tiovx/gsttiovxmiso.c

Setting property for src pad fails since the
get child by name does not take care of src pad.
Fix this by handling src pads in get child
callback

gst-libs: tiovx: miso: Fix child proxy for src pad

---

ext/tiovx/gsttiperfoverlay.cpp

Add protection to set caps function so that parameters are not reconfigured

ext: tiovx: tiperfoverlay: Protect Set Caps function.

---

ext/tiovx/gsttidlpostproc.cpp

Implement child proxy to enable setting pad properties like pool-size, signals etc..

ext: tiovx: postproc: Add child proxy to set pad properties

---

ext/tiovx/gsttiovxldc.c
ext/tiovx/gsttiovxmultiscaler.c
ext/tiovx/gsttiovxmultiscalerpad.c
ext/tiovx/gsttiovxmultiscalerpad.h
gst-libs/gst/tiovx/gsttiovxsimo.c
gst-libs/gst/tiovx/gsttiovxsimo.h

Add support for setting region of interest for
each src pad
Depends on :
https://github.com/TexasInstruments/edgeai-tiovx-modules/pull/90

ext: tiovx: multiscaler: Add support for ROI

---

ext/tiovx/gsttiperfoverlay.cpp

tiperfoverlay: Add title to dump csv file

---

ext/tiovx/gsttiperfoverlay.cpp

tiperfoverlay: Remove frame count rendering

---

ext/tiovx/gsttidlpostproc.cpp

Fix query and event callbacks were not handled properly because of which caps negotiation was failing for
some cases. Ex. postproc->encode

ext: tiovx: tidlpostproc: Fix query and event callbacks

---

ext/tiovx/gsttidlinferer.cpp

Add support to specify C7x target for inference offload

ext: tiovx: dlinferer: Add support to specify C7x target

---

ext/tiovx/gsttiperfoverlay.cpp

Remove mcu load. Also display total ddr bw.

tiperfoverlay: Remove mcu loads

---

ext/tiovx/gsttiperfoverlay.cpp

ext: tiovx: perfoverlay: Change the default main title

---

ext/tiovx/gsttiovxldc.c

Fix get_src_caps and sink_caps call back to add support from UYVY to NV12, since HW supports it.
Also init sensor only for dcc mode and support not setting lut-file for enabling 1to1 remap

ext: ldc: Add support for colorconversion UYVY -> NV12

---

ext/tiovx/gsttidlpostproc.cpp

Add support to display model-name on top of frame

tidlpostproc: Add support to display model-name

---

ext/tiovx/gsttiperfoverlay.cpp

Use perf_stats utils in edgeai-apps-utils to calculate mpu load. If SOC supports openvx, then display c7x, hwa and ddr load as well.
Also use edgeai-apps-utils library for graphics rendering instead of edgeai-post-proc.

ext: tiovx: gsttiperfoverlay: Use tiovx only if available

---

ext/tiovx/gsttiovx.c
ext/tiovx/gsttiscaler.c
ext/tiovx/gsttiscaler.h
ext/tiovx/meson.build

Add tiscaler plugin (non-openvx).
Uses API provided by edgeai-apps-utils library.

ext: tiovx: Add tiscaler plugin

---

ext/tiovx/gstticolorconvert.c

This also fixes issue where ticolorconvert
does not work with v4l2h264enc

ext: tiovx: ticolorconvert: Fix passthrough bug

---

ext/ti/gsttiscaler.c

Add property for interpolation method.
0 - Nearest Neighbour
1 - Bilinear (Default)

ext: ti: tiscaler: Add property for interpolation method

---

ext/ti/gsttimosaic.c

Handle EOS event. Add property to enable
or disable repetation of buffers after eos
is received on a pad.

ext: ti: timosaic: Handle EOS event

---

ext/tiovx/gsttiovxdlcolorblend.c
ext/tiovx/gsttiovxdlcolorconvert.c
ext/tiovx/gsttiovxdlpreproc.cpp

Change TIVX_CPU_ID_A72_0 to TIVX_CPU_ID_MPU_0
Change TIVX_TARGET_A72_* to TIVX_TARGET_MPU_*
This change was made in account for the change
made in TIOVX

Change TIVX_CPU_ID_A72_0 and TIVX_TARGET_A72_*

---

meson.build

with some issues in dependencies

meson: Remove -Werror to make builds work

---

ext/ti/gsttiscaler.c

Add support to crop and then scale

ext: ti: tiscaler: Add support to crop.

---

ext/ti/gstticolorconvert.c
ext/tiovx/gsttiovxdlcolorconvert.c
gst-libs/gst/tiovx/gsttiovxmiso.c
gst-libs/gst/tiovx/gsttiovxmiso.h
gst-libs/gst/tiovx/gsttiovxsiso.c
gst-libs/gst/tiovx/gsttiovxsiso.h

Implements EDGEAI_ROBOTICS-1140

gstticolorconvert/gsttiovxdlcolorconvert: Add support for u82nv12

---

meson.build

This reverts commit 4ade199ae461cbf092075a77b89497102781a7be.

Revert "meson: Remove -Werror to make builds work"

---

ext/ti/gsttidlpostproc.cpp

Post process api changed which added optional argument for getting post process result as text. Add requeust text pad with text/x-raw caps that can be used to stream the post process result text in JSON format.

ext: ti: postproc: Add text pad for getting post proc result

---

ext/ti/gsttiperfoverlay.cpp

Use overlay_perf utils in edgeai_apps_utils

ext: ti: perfoverlay: Use overlayperf utils in apps_utils

---

ext/ti/gsttiperfoverlay.cpp

Also some cleanup and bug fixes

ext: ti: perfoverlay: Add support to dump mcu loads

---

ext/tiovx/gsttiovxisp.c

ext: tiovx: isp: Skip AE if mode is set to manual

---

ext/ti/gsttidlinferer.cpp

plugin now supports the option to print the TIDL level logs

gsttidlinferer: Added debug-level parameter in plugin

---

gst-libs/gst/tiovx/gsttiovximagebufferpool.c
gst-libs/gst/tiovx/gsttiovxutils.c

alignement can be configured via caps using
stride-y-align and stride-x-align props

gst-libs: tiovx: Add support to align strides for video/x-raw caps

---

ext/tiovx/gsttiovxmultiscaler.c

For NV12, when num_outputs <= 2

ext: tiovx: multiscaler: Enable simultaneous processing
