TexasInstruments/edgeai-gst-plugins

- gst-libs/gst/tiovx/gsttiovxmeta.c
This change fixes an error message that appeared when using a pool size larger than 8, for example:
```
reset; GST_DEBUG="*ti*:2" gst-launch-1.0 videotestsrc is-live=true num-buffers=20 ! "video/x-raw,format=NV12,width=1280,height=720" ! tiovxmultiscaler name=multi src_0::pool-size=16  multi. ! "video/x-raw,format=NV12,width=640,height=480" !  filesink location=/tmp/frames.bin
```
which caused the following error:
```
74627.984019 s:  VX_ZONE_ERROR:[vxMapImagePatch:2016] No available image maps
74627.984044 s:  VX_ZONE_ERROR:[vxMapImagePatch:2017] May need to increase the value of TIVX_IMAGE_MAX_MAPS in tiovx/include/TI/tivx_config.h
```
> Free image patch after determining the stride

- ext/tiovx/gsttiovxmultiscaler.c
Previously the case where the filter received in gst_tiovx_multi_scaler_get_sink_caps could be NULL. Proposed fix for #30
> Add check to avoid assertions thrown due to filter being NULL

- gst-libs/gst/tiovx/gsttiovxallocator.c
- gst-libs/gst/tiovx/gsttiovxallocator.h
- gst-libs/gst/tiovx/gsttiovxutils.c
Using gst_buffer_copy will create a new memory appended to our buffer,
we are now manually copying the memory from the input buffer to ensure
valid data in the meta.
> Make a manual copy to TIs memory

- ext/tiovx/gsttiovxcolorconvert.c
- ext/tiovx/gsttiovxdlpreproc.c
- gst-libs/gst/tiovx/gsttiovxsiso.c
- gst-libs/gst/tiovx/gsttiovxsiso.h
If caps are equal, depending on subclass analysis, the modules
are deinit/init in order to accept new caps.
> Compare caps before modules reinitialization

- README.md
The project can now be built inside the container by following the native build instructions, it just requires the modules to me rebuilt inside the container. 
This works as long as the container is built using the scripts provided by TI since it binds the required volumes inside the container.
> Update docker README instructions

- ext/tiovx/gsttiovxmosaic.c
- gst-libs/gst/tiovx/gsttiovxmiso.c
- gst-libs/gst/tiovx/gsttiovxmiso.h
This avoids popping buffers that were not processed, this solves #110
> Mosaic max framerate

- README.md
Fix cross compile steps to override default PKG_CONFIG_PATH which points to 
host path
> crossbuild: Fix steps in readme to unset PKG_CONFIG_PATH

- gst-libs/gst/tiovx/gsttiovx.h
- pkgconfig/ti_vision_apps.pc
- tests/check/libs/gsttiovxmiso.c
- tests/check/libs/gsttiovxsimo.c
- tests/check/libs/gsttiovxsiso.c
TI/j7.h is deprecated and merged in TI/tivx.h
fix the same. Also remove the dlr dependency for
vision apps
> TI/j7.h is deprecated in PSDKR 8.4 align to the same

- gst-libs/gst/tiovx/gsttiovximagemeta.c
- gst-libs/gst/tiovx/gsttiovxrawimagemeta.c
- gst-libs/gst/tiovx/gsttiovxtensormeta.c
- gst-libs/gst/tiovx/gsttiovxutils.c
- gst-libs/gst/tiovx/gsttiovxutils.h
Create a copy of exemplars before vxMapping buffers and release the copy after unmap, this is required to free any memory allocated while Mapping
> gst-libs: meta: Fix mem leak while Mapping buffers

- ext/tiovx/gsttiovxldc.c
Add properties to configure crop start x and y coordinate when output resolution is configured less than input
> ext: tiovx: ldc: Add properties to configure crop params

- ext/tiovx/gsttiovxcolorconvert.c
- ext/tiovx/gsttiovxdlcolorconvert.c
Fix the transform caps to remove all irrelavant
fields and keep only required fields like
width, height, format and framerate
Keeping all fields with resulted in lot of
issues in caps negotiation. For example caps
negotiation failed with USB cam and v4l2enc
because of colorimetry field
> ext: tiovx :colorconverts: Fix the transform caps

- ext/tiovx/gsttiperfoverlay.cpp
FPS Calculated in double, round to nearest integer
> ext: tiovx: gsttiperfoverlay: Round fps to nearest integer

- ext/tiovx/gsttiovx.c
- ext/tiovx/meson.build
- meson.build
- meson_options.txt
Add option to enable or disable DL inferer plugins, this is useful to build other plugins without dl inferer dependency
> mesom: Add option to enable or disable DL inferer plugins

- ext/tiovx/gsttidlinferer.cpp
ONNX OD models were failing because of an issue in reading output dims, fix the same
> ext: tiovx: dlinferer: Fix issue with ONNX OD models

- ext/tiovx/gsttiperfoverlay.cpp
- tags
Add support to dump stats on terminal. Also, remove option of overlay text, since its redundant
> ext: tiovx: tiperfoverlay: Add support to dump stats on terminal

- ext/tiovx/gsttiovxisp.c
- gst-libs/gst/tiovx/gsttiovxrawimagebufferpool.c
- gst-libs/gst/tiovx/gsttiovxutils.c
Get meta before and after from caps insted of property, which makes to simpler to validate and create exemplars using caps
> ext: tiovx: isp: Get meta before and after from caps

- ext/tiovx/gsttiovxdlpreproc.c
- gst-libs/gst/tiovx/gsttiovxbufferutils.c
- gst-libs/gst/tiovx/gsttiovxsensormeta.c
- gst-libs/gst/tiovx/gsttiovxutils.c
- gst-libs/gst/tiovx/gsttiovxutils.h
To improve the latency while importing buffers
from non tiovx buffer pools
> gst-libs: Use neon intrinsics for memcpy

- ext/tiovx/gsttiperfoverlay.cpp
Calling reset right after calculating ddr stats
zeroed out the data in self->ddr_load. Make a
copy to preserve it.
> ext: tiovx: perfoverlay: Fix DDR Stats read bug

- ext/ti/gsttimosaic.c
Set clear count to a default value if max_buffers
info is not by downstream pool
> ext: ti: mosaic: Set default clear count

- ext/ti/gsttidlinferer.cpp
- ext/ti/gsttidlpostproc.cpp
- ext/ti/gsttidlpreproc.cpp
- ext/ti/gsttiperfoverlay.cpp
- ext/tiovx/gsttiovxdlpreproc.cpp
glib.h has __cplusplus macro and behaves differently for .c and .cpp files, so add this to cpp files
before extern C linking to avoid it being added
inside extern C block
> ext: ti*: *.cpp: Add glib.h header file include

- ext/tiovx/gsttiovxmosaic.c
Remove hardcoding set to 8. Instead use macro to get the max allowed input
> gst: tiovx: mosaic: Remove hardcoding for input_arr_user

- ext/ti/gsttiperfoverlay.cpp
- gst-libs/gst/ti/gsttidloutmeta.c
- gst-libs/gst/tiovx/gsttiovximagemeta.c
- gst-libs/gst/tiovx/gsttiovxmuxmeta.c
- gst-libs/gst/tiovx/gsttiovxpyramidmeta.c
- gst-libs/gst/tiovx/gsttiovxrawimagemeta.c
- gst-libs/gst/tiovx/gsttiovxtensormeta.c
Remove volatile from GType as g_once_init_enter
ignores volatile keyword
> Remove volatile from GType

- gst-libs/gst/tiovx/gsttiovxbufferpool.c
All tiovx elements configures both min and max buffers equal to pool size resulting allocation of exact pool size number of buffers. whereas if pool size is configured by some upstream element ex: v4l2h264dec it might configure different min and max. This is resulting in some issue with HW decoder piplines in j721s2, j784s4 and am62a, since there is a limitation in dmabuf import feature cannot work with newly allocated buffers
Fix this by setting max and min, in bufferpool set config
> HACK: gst-libs: tiovxbufferpool: Set max buffers to min

- gst-libs/gst/tiovx/gsttiovxmiso.c
This reverts commit 63024e5e320fa47e7a4e0e9de94e324f802c08b3.
This was done as a workaround for cpature not working with dmabuf import. Root cause for this was found in a patch in gst plugins good and fixed now
> Revert "tiovxmiso: Increase minimum pool size"

- gst-libs/gst/tiovx/gsttiovxbufferpool.c
This reverts commit 450f6280e2f0ebca6ff9f4c9f4a74902f3fba293.
This is now handled in gst-plugins-good patch in yocto layer
> Revert "HACK: gst-libs: tiovxbufferpool: Set max buffers to min"

- ext/tiovx/gsttiovxisp.c
[ISS-447] Limit ov2312 sensor gain between 16 and 42 in order to avoid green artifacts from sensor from high sensor gain values.
> Update gsttiovxisp.c for ov2312 sensor gain

- ext/tiovx/gsttiovxmosaic.c
- gst-libs/gst/tiovx/gsttiovximagemeta.c
Fixes commit c901be6750f57742ce2afa013b84ebf2b16e5639. Fix data type for num_planes guint -> vx_size
> Fixes "ext: tiovx: mosaic: Use vxQueryImage to get stride info"

- ext/tiovx/gsttiovxisp.c
This Fixes commit 97d1758536e823252ea0f17e0fe1978b379994e3. Set default for bypass-nsf4 as FALSE
> Fixes "tiovxisp: Add properties to set some of the ISP params"

- ext/ti/gsttiperfoverlay.cpp
gchar *cpu_name -> const gchar *cpu_name
> ext: ti: tiperfoverlay: Fix a warning with updated in apps_utils

- gst-libs/gst/tiovx/gsttiovxallocator.c
This is a unnecessary operation, since these buffers are not required to be cleared
> gst-libs: tiovxallocator: Remove memsetting buffers after allocation

- ext/tiovx/gsttiovxdof.c
- ext/tiovx/gsttiovxisp.c
- ext/tiovx/gsttiovxmosaic.c
- ext/tiovx/gsttiovxsde.c
- gst-libs/gst/tiovx/gsttiovxmiso.c
- gst-libs/gst/tiovx/gsttiovxmiso.h
- tests/check/libs/gsttiovxmiso.c
Some nodes need objext array to be enqueued, instead of first element
> miso: Fix enqueue and setting ref list
